env:
  browser: true
  es2021: true
extends:
  - 'eslint:recommended'
  - 'plugin:json/recommended'
plugins:
  - 'json'
parserOptions:
  ecmaVersion: 12
  sourceType: module
rules:
  indent:
    - error
    - 4
  no_tabs: 0
  quotes:
    - error
    - double
  semi:
    - error
    - always
